### ISSUE TITLE
The preview tab closes when I move the focus to a different split in vim

### ISSUE THREAD

**Issue by caenrique** [davidgranstrom/nvim-markdown-preview#1]
I have multiple panes open and visible in vim, and after executing `:MarkdownPreview` and then switching to a different split pane, the preview tab in the browser closes automatically.
Is this the intended behaviour?

**Comment by davidgranstrom** [comment]
I can not reproduce the issue here. Do you trigger `MarkdownPreview` via an `autocmd`, or do you call it from the command line area?

**Comment by caenrique** [comment]
I just execute the command
