### ISSUE TITLE
Doesn't open in browser

### ISSUE THREAD

**Issue by arminveres** [davidgranstrom/nvim-markdown-preview#10]
Hi there,
I installed this yesterday and it runs flawlessly on my laptop (fedora 35) but on my desktop (f35 too), it doesn't start a tab in my browser.
The node server is just running in the background, fans ramping up, without anything happening.
I obviously installed the prerequisites but I don't know what the problem could be.
Haven't found anything in the neovim logs either.
I'm using neovim 0.6.0 on both machines.
Did I miss something?

EDIT: Additionally images are not previewable on my laptop since about yesterday.

**Comment by davidgranstrom** [comment]
Hi 👋 

Not sure what could be the cause of this, but presumably it has something to do with `live-server`. What version are you using? 

```
$ live-server --version
live-server 1.2.1
```

**Comment by arminveres** [comment]
Hi,
Thanks for replying, for whatever reason, after removing and reinstalling it multiple times, it started working.
But before it worked, it displayed random gibberish with `live-server --version`, so you were right. 
Sorry for bothering!
