### ISSUE TITLE
[Feature Request] Enable live-server alternative

### ISSUE THREAD

**Issue by David-Else** [davidgranstrom/nvim-markdown-preview#15]
`live-server` is very old and unmaintained. It has know security vulnerabilities: https://github.com/tapio/live-server/issues/390

It would be nice to be able to use an alternative, https://github.com/lukejacksonn/servor#readme looks ideal. It has zero dependencies.

**Comment by davidgranstrom** [comment]
Thanks for bringing this to my attention. I haven't used the application you have linked but I will have a look and see how much work would be involved to make a switch.

**Comment by davidgranstrom** [comment]
@David-Else I recently had a chance to try out `servor` and it seems like a possible alternative, although currently its missing an important feature (at least for this plugin) namely to be able to serve content from multiple paths. I saw that there was a PR implementing this feature so I will give that a try.

**Comment by David-Else** [comment]
@davidgranstrom Great news you checked it out! I found Servor in https://css-tricks.com/comparing-the-new-generation-of-build-tools/ , I don't know of any other replacements for live-server, but I have not searched much. Servor does look nice.

**Comment by ghost** [comment]
Hi! Also an alternative is https://www.npmjs.com/package/@compodoc/live-server it's just a fork done by @compodoc and development is more active and fixed security problems updating all dependencies. Migrations is just remove live-server and add @compodoc/live-server, the rest just continue working in the same way.

**Comment by davidgranstrom** [comment]
@jhernandez-at-wiris Thanks, just tested and it looks like a great alternative! I'll make a note to update the installation instructions in the README.

**Comment by davidgranstrom** [comment]
Added a note to the README to use the @compodoc/live-server fork and linked to this issue.
